### ISSUE TITLE
Error reproducing

### ISSUE THREAD

**Issue by jordanhart** [ssloxford/seeing-red#5]
Hi!

I went through the reproducing evaluation steps on a macbook pro running Big Sur, and currently getting this error running step 6.
```
Traceback (most recent call last):
  File "signal_extractor.py", line 241, in <module>
    for file in sorted(user_files))
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.6/dist-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.
```
Any advice would be appreciated. The closest thread I found is here https://github.com/scikit-learn-contrib/skope-rules/issues/18. The args.number_of_cpus is 2. 

Edit: When removing the Parallel code on line 239 of signal_extractor.py and running, the issue disappears. Probably something to look into.
Thanks!

**Comment by giuliolovisotto** [comment]
Hi Jordan, 

I'm glad you solved it! Unfortunately as mentioned in the readme we can't guarantee that the code runs everywhere, that's why we provide instruction to set it up in a docker container.

We might include the option to run this without parallelisation with joblib if this becomes a common problem but for now I'll close this.
